# Generated by Django 3.2.12 on 2022-03-12 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_name', models.CharField(max_length=100)),
                ('main_title', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200)),
                ('question_body', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 3, 12, 12, 13, 22, 536549))),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.title')),
            ],
        ),
    ]
