# Generated by Django 3.2.12 on 2022-03-12 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('brief', models.TextField()),
                ('image_path', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 3, 12, 9, 13, 22, 535151, tzinfo=utc))),
            ],
        ),
    ]
