# Generated by Django 3.2.12 on 2022-03-26 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 26, 15, 33, 35, 6905, tzinfo=utc)),
        ),
    ]
