# Generated by Django 3.2.12 on 2022-03-30 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 21, 6, 3, 272974, tzinfo=utc)),
        ),
    ]
