# Generated by Django 3.2.12 on 2022-03-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extra_css_classes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='html_anchor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
